export const QUITAR_CATEGORIA = 'QUITAR_CATEGORIA';
export const CAMBIO_CATEGORIA = 'QUITAR_CATEGORIA';

export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';

export const LOGIN_PREVIO = 'LOGIN_PREVIO';

export const LIMPIAR_DATOS_SESION = 'LIMPIAR_DATOS_SESION';
